$(document).ready(function () {

    var $p1 = $('#p1');
    var $p2 = $('#p2');
    var $p3 = $('#p3');
    var $p4 = $('#p4');
    var $p5 = $('#p5');
    var $p6 = $('#p6');
    var $p7 = $('#p7');
    var $p8 = $('#p8');
    var $p9 = $('#p9');
    var $p10 = $('#p10');
    var $p11 = $('#p11');
    var $p12 = $('#p12');
    var $p13 = $('#p13');
    var $p14 = $('#p14');
    var $p15 = $('#p15');
    var $p16 = $('#p16');
    var $p17 = $('#p17');
    var $p18 = $('#p18');
    var $p19 = $('#p19');

    var $text1 = $("#text-info1");
    var $text2 = $("#text-info2");
    var $text3 = $("#text-info3");
    var $text4 = $("#text-info4");
    var $text5 = $("#text-info5");
    var $text6 = $("#text-info6");
    var $text7 = $("#text-info7");
    var $text8 = $("#text-info8");
    var $text9 = $("#text-info9");
    var $text10 = $("#text-info10");
    var $text11 = $("#text-info11");
    var $text12 = $("#text-info12");
    var $text13 = $("#text-info13");
    var $text14 = $("#text-info14");
    var $text15 = $("#text-info15");
    var $text16 = $("#text-info16");
    var $text17 = $("#text-info17");
    var $text18 = $("#text-info18");
    var $text19 = $("#text-info19");

    $('#p1').click(function () {
        $p1.addClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeIn("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p2').click(function () {
        $p1.removeClass('active');
        $p2.addClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeIn("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p3').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.addClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeIn("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p4').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.addClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeIn("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p5').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.addClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeIn("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p6').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.addClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeIn("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p7').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.addClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeIn("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p8').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.addClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeIn("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p9').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.addClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeIn("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p10').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.addClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeIn("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p11').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.addClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeIn("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p12').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.addClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeIn("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p13').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.addClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeIn("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p14').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.addClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeIn("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p15').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.addClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeIn("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p16').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.addClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeIn("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p17').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.addClass('active');
        $p18.removeClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeIn("fast");
        $text18.fadeOut("fast");
        $text19.fadeOut("fast");
    });

    $('#p18').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.addClass('active');
        $p19.removeClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeIn("fast");
        $text19.fadeOut("fast");
    });

    $('#p19').click(function () {
        $p1.removeClass('active');
        $p2.removeClass('active');
        $p3.removeClass('active');
        $p4.removeClass('active');
        $p5.removeClass('active');
        $p6.removeClass('active');
        $p7.removeClass('active');
        $p8.removeClass('active');
        $p9.removeClass('active');
        $p10.removeClass('active');
        $p11.removeClass('active');
        $p12.removeClass('active');
        $p13.removeClass('active');
        $p14.removeClass('active');
        $p15.removeClass('active');
        $p16.removeClass('active');
        $p17.removeClass('active');
        $p18.removeClass('active');
        $p19.addClass('active');
        $text1.fadeOut("fast");
        $text2.fadeOut("fast");
        $text3.fadeOut("fast");
        $text4.fadeOut("fast");
        $text5.fadeOut("fast");
        $text6.fadeOut("fast");
        $text7.fadeOut("fast");
        $text8.fadeOut("fast");
        $text9.fadeOut("fast");
        $text10.fadeOut("fast");
        $text11.fadeOut("fast");
        $text12.fadeOut("fast");
        $text13.fadeOut("fast");
        $text14.fadeOut("fast");
        $text15.fadeOut("fast");
        $text16.fadeOut("fast");
        $text17.fadeOut("fast");
        $text18.fadeOut("fast");
        $text19.fadeIn("fast");
    });
});








//FOR MOBILE VERSION









$(document).ready(function () {

    var $r1 = $('#r-1');
    var $r2 = $('#r-2');
    var $r3 = $('#r-3');
    var $r4 = $('#r-4');
    var $r5 = $('#r-5');
    var $r6 = $('#r-6');
    var $r7 = $('#r-7');
    var $r8 = $('#r-8');
    var $r9 = $('#r-9');
    var $r10 = $('#r-10');
    var $r11 = $('#r-11');
    var $r12 = $('#r-12');
    var $r13 = $('#r-13');
    var $r14 = $('#r-14');
    var $r15 = $('#r-15');
    var $r16 = $('#r-16');
    var $r17 = $('#r-17');
    var $r18 = $('#r-18');
    var $r19 = $('#r-19');

    var $t1 = $("#content1");
    var $t2 = $("#content2");
    var $t3 = $("#content3");
    var $t4 = $("#content4");
    var $t5 = $("#content5");
    var $t6 = $("#content6");
    var $t7 = $("#content7");
    var $t8 = $("#content8");
    var $t9 = $("#content9");
    var $t10 = $("#content10");
    var $t11 = $("#content11");
    var $t12 = $("#content12");
    var $t13 = $("#content13");
    var $t14 = $("#content14");
    var $t15 = $("#content15");
    var $t16 = $("#content16");
    var $t17 = $("#content17");
    var $t18 = $("#content18");
    var $t19 = $("#content19");

    $('#r-1').click(function () {
        $r1.toggleClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.toggle("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-2').click(function () {
        $r1.removeClass('active');
        $r2.toggleClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.toggle("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-3').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.toggleClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.toggle("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-4').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.toggleClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.toggle("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-5').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.toggleClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.toggle("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-6').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.toggleClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.toggle("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-7').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.toggleClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.toggle("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-8').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.toggleClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.toggle("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-9').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.toggleClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.toggle("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-10').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.toggleClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.toggle("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-11').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.toggleClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.toggle("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-12').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.toggleClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.toggle("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-13').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.toggleClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.toggle("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-14').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.toggleClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.toggle("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-15').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.toggleClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.toggle("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-16').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.toggleClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.toggle("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-17').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.toggleClass('active');
        $r18.removeClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.toggle("fast");
        $t18.fadeOut("fast");
        $t19.fadeOut("fast");
    });

    $('#r-18').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.toggleClass('active');
        $r19.removeClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.toggle("fast");
        $t19.fadeOut("fast");
    });

    $('#r-19').click(function () {
        $r1.removeClass('active');
        $r2.removeClass('active');
        $r3.removeClass('active');
        $r4.removeClass('active');
        $r5.removeClass('active');
        $r6.removeClass('active');
        $r7.removeClass('active');
        $r8.removeClass('active');
        $r9.removeClass('active');
        $r10.removeClass('active');
        $r11.removeClass('active');
        $r12.removeClass('active');
        $r13.removeClass('active');
        $r14.removeClass('active');
        $r15.removeClass('active');
        $r16.removeClass('active');
        $r17.removeClass('active');
        $r18.removeClass('active');
        $r19.toggleClass('active');
        $t1.fadeOut("fast");
        $t2.fadeOut("fast");
        $t3.fadeOut("fast");
        $t4.fadeOut("fast");
        $t5.fadeOut("fast");
        $t6.fadeOut("fast");
        $t7.fadeOut("fast");
        $t8.fadeOut("fast");
        $t9.fadeOut("fast");
        $t10.fadeOut("fast");
        $t11.fadeOut("fast");
        $t12.fadeOut("fast");
        $t13.fadeOut("fast");
        $t14.fadeOut("fast");
        $t15.fadeOut("fast");
        $t16.fadeOut("fast");
        $t17.fadeOut("fast");
        $t18.fadeOut("fast");
        $t19.toggle("fast");
    });
});